colorScheme = "ocean"

defaultAppearance = "light"

autoSwitchAppearance = true

enableSearch = true

enableCodeCopy = true

[author]
name = "Jenna Lu"
image = "images/profile.jpg"
headline = "Statistics Student | Biomedical Data Science Researcher"
bio = "Exploring how statistics and AI can reveal insights hidden within complex biological data"
links = [
  { github = "https://github.com/jen-h-lu" },
  { linkedin = "https://www.linkedin.com/in/jenna-h-lu/" }
]

showAppearanceSwitcher = true
hideAuthor = false

[article]
showHero = true
width = "wide"
showDate = false
showDateUpdated = false


[list]
showCards = true
groupByYear = false
cardView = true

customCSS = ["css/custom.css"]

[homepage]
layout = "profile"
showRecent = false